(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "TAB") 'yas-expand)
(global-set-key (kbd "<f1>") 'next-multiframe-window-wrapper)
(global-set-key  [f12]   (read-kbd-macro "C-u M-."))
(global-set-key (kbd "<f2>") 'delete-other-windows)
(global-set-key (kbd "<escape>") 'delete-window)
(global-set-key (kbd "C-S-<up>") 'move-line-up)
(global-set-key (kbd "C-S-<down>") 'move-line-down)
(global-set-key (kbd "C-/") 'comment-or-uncomment-region-or-line)
(global-set-key [home] 'smart-beginning-of-line)
(global-set-key (kbd "<f9>") 'sr-speedbar-toggle)
(global-set-key (kbd "<f10>") 'dired)
(global-set-key (kbd "<C-mouse-4>") 'text-scale-increase)
(global-set-key (kbd "<C-mouse-5>") 'text-scale-decrease)
