(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "TAB") 'yas-expand)
(global-set-key (kbd "<f1>") 'next-multiframe-window)
(global-set-key  [f12]   (read-kbd-macro "C-u M-."))
(global-set-key (kbd "<escape>") 'delete-other-windows)
(global-set-key (kbd "C-S-<up>") 'move-line-up)
(global-set-key (kbd "C-S-<down>") 'move-line-down)
(global-set-key (kbd "C-/") 'comment-or-uncomment-region-or-line)
(global-set-key [home] 'smart-beginning-of-line)
